steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/syntax-hilight-battle-api:$COMMIT_SHA",
        ".",
      ]
    timeout: 1000s
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/syntax-hilight-battle-api:$COMMIT_SHA"]
    timeout: 1000s
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "syntax-hilight-battle-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/syntax-hilight-battle-api:$COMMIT_SHA"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
    timeout: 1000s
images:
  - "gcr.io/$PROJECT_ID/syntax-hilight-battle-api:$COMMIT_SHA"
timeout: 1200s
